# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PLAT=manylinux1_x86_64
           MANYLINUX=1
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
           PLAT=manylinux1_i686
           MANYLINUX=1
    - sudo: required
      arch: arm64-graviton2
      group: edge
      virt: lxd
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
           PLAT=manylinux2014_aarch64
           MANYLINUX=1
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64
           MANYLINUX=1
    - os: linux
      python: 2.7
      env:
        - PYFLAKES=1
        - PEP8=1
        - MANYLINUX=0
      before_install:
        - pip install pep8==1.6.2
        - pip install pyflakes
      script:
        - PYFLAKES_NODOCTEST=1 pyflakes scrypt.py | grep -E -v 'unable to detect undefined names|assigned to but never used|imported but unused|redefinition of unused' > test.out; cat test.out; test \! -s test.out
        - pep8 scrypt
    - os: linux
      python: 3.6
      env:
        - TOXENV=py36
        - MANYLINUX=0
    - os: linux
      python: 3.6
      env:
        - USE_WHEEL=1
        - LINUX_WHEEL=1
        - TOXENV=py36
        - MANYLINUX=0
#      addons:
#        apt:
#          packages:
#            - patchelf
    - os: linux
      python: 3.6
      env:
        - USE_SDIST=1
        - TOXENV=py36
        - MANYLINUX=0
    - os: osx
      osx_image: xcode9.4
      language: objective-c
      env:
        - USE_WHEEL=1
        - TRAVIS_PYTHON_VERSION=3.6
        - MAC_WHEEL=1
        - MANYLINUX=0
        - TOXENV=py36
        - SCRYPT_SUPPRESS_LINK_FLAGS=1
    - os: osx
      osx_image: xcode10.2
      language: objective-c
      env:
        - USE_WHEEL=1
        - TRAVIS_PYTHON_VERSION=3.7
        - MAC_WHEEL=1
        - MANYLINUX=0
        - TOXENV=py37
        - SCRYPT_SUPPRESS_LINK_FLAGS=1
    - os: osx
      osx_image: xcode10.2
      language: objective-c
      env:
        - USE_WHEEL=1
        - TRAVIS_PYTHON_VERSION=3.8
        - MAC_WHEEL=1
        - MANYLINUX=0
        - TOXENV=py38
        - SCRYPT_SUPPRESS_LINK_FLAGS=1

cache: pip

before_install:
  - uname -a
  - df -h
  - ulimit -a
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source util/travis_osx_install.sh; fi
  - ccache -s
  - |
    if [ "${MANYLINUX}" == "0" ]; then
        which python; python --version
        pip install --upgrade pip
        pip install --upgrade wheel
        mkdir ${TRAVIS_BUILD_DIR}/wheelhouse
        pip install --upgrade auditwheel
    else
        docker pull $DOCKER_IMAGE
    fi
  # Set numpy version first, other packages link against it
  #- pip install Cython matplotlib nose coverage codecov futures
  - set -o pipefail

script:
  # Define a fixed build dir so next step works
  - |
    if [ "${LINUX_WHEEL}" == "1" ]; then
        pip wheel . -v
    fi
  - |
    if [ "${MAC_WHEEL}" == "1" ]; then
       export LDFLAGS="/usr/local/opt/openssl\@1.1/lib/libssl.a /usr/local/opt/openssl\@1.1/lib/libcrypto.a"
       export CFLAGS="-I/usr/local/opt/openssl\@1.1/include"
       pip wheel . -v
       delocate-listdeps scrypt*.whl
       delocate-wheel -v scrypt*.whl
       delocate-listdeps --all scrypt*.whl
    fi
  - |
#    if [ "${LINUX_WHEEL}" == "1" ]; then
#       auditwheel show scrypt*.whl
#       auditwheel repair scrypt*.whl
#    fi
  - |
    if [ "${MANYLINUX}" == "1" ]; then
        docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
    elif [ "${USE_WHEEL}" == "1" ]; then
        # Need verbose output or TravisCI will terminate after 10 minutes
        #pip wheel . -v
        cp *.whl ${TRAVIS_BUILD_DIR}/wheelhouse/
        pip install scrypt*.whl -v
        python setup.py test
    elif [ "${USE_SDIST}" == "1" ]; then
        python setup.py sdist
        # Move out of source directory to avoid finding local scrypt
        pushd dist
        pip install scrypt* -v
        popd
        python setup.py test
    else
        #CFLAGS="--coverage" python setup.py build --build-lib build/lib/ --build-temp build/tmp/
        python setup.py build
        python setup.py test
    fi

deploy:
  provider: releases
  api-key:
    secure: "Xv8A881fwJ44B3u7PYnouvVKeexqdSPDL5wQe98SeVNT7+gaPINiSPiTQc8Pr8K0rMogYVkC6m+2Q1G+YOZJz9k2LBhX1pdgGi8qUk9Zq59UVLwWH8tHs6yyXdu+AvKrxZaOmfsDDdilJknYBaiH9GO13TX+IiTqixt6iJNFMU6HqR0aaqIXi6ZhSNTLRjODEXRfUovJiCqppo9fcfbQC4Fos1fzlaGc5ccLy+VwEzYyLY7EgLrbZkFrvJSrDD5VJnZ/yuKD9FIvog5vyUE0BMs0eRtd5R1q6e1xtTyNArZa86OXfOzIj1vgkrq6JVnXBnFX7NdmBRhocwW6WByZ2ucd7+Za1w+NrS5sRRcTSfpfjUMx8AwUMIXJ9wj3RzTvaK6+/58ScgxrMZVGc4luT4NUaVjowMt86PVWfMCFtGKRBIYD+il9G9I1hjFQtkFX0EaZ2v2tQbiL+J1rHEkVnMDJ8hVatpLZFQ45/91/sVw8rkNZjQE1z7psKS9KPpEPt2Kvfao9G7Lnj4n42PgaM+VTeVWgUiNs3g8qj+04IsBxXGX+/iRlZUOMOWg0EmeGqBjz4RftGRkuWh7fMxF9uTHpXWWuFUH8iNL/Lkb2cNIpobzLCG8qtUhe2LdRfT2De/6s6tlnEh72zaQEtXETatgtDCdiurpnBQxV5DVSuuU="
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/wheelhouse/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
